// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjRRMcusL5mMgWfu3yefNSEw1vBuODk-c',
    appId: '1:471744208296:web:fb4dbff93b8253ad0cd19d',
    messagingSenderId: '471744208296',
    projectId: 'recipe-app-e4e2c',
    authDomain: 'recipe-app-e4e2c.firebaseapp.com',
    storageBucket: 'recipe-app-e4e2c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ1fveKAXRDwKXkJLsB1lubc3c8RcEmiQ',
    appId: '1:471744208296:android:a1157b5e8ee772900cd19d',
    messagingSenderId: '471744208296',
    projectId: 'recipe-app-e4e2c',
    storageBucket: 'recipe-app-e4e2c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEwuQsXAgPOVaUBQ41zlW2ZWYdCXrk4pg',
    appId: '1:471744208296:ios:f52ca35105e6e47b0cd19d',
    messagingSenderId: '471744208296',
    projectId: 'recipe-app-e4e2c',
    storageBucket: 'recipe-app-e4e2c.firebasestorage.app',
    iosBundleId: 'com.example.recipeApp',
  );

}